# 13.异常捕获与处理


## 异常捕获

异常处理规则

1. 不要过度使用异常，不要使用异常代替流程控制，该要提示的就要给出提示和错误处理方法
2. 不要用过于庞大的try语句块，永远只捕获那些可能会抛出异常的语句块
3. 不要忽略捕获到的异常，要对异常采取相应措施
4. 尽量只捕获精确的异常类型，而不是模糊的Exception
5. 如果出现了预期外的异常，让程序早点儿崩溃也未必是件坏事



```python
try:
    10 / 0 
except ZeroDivisionError: 
    print('捕获异常成功')
```


```python
try: 
    print(a) 
    10 / 0 
except ZeroDivisionError: 
    print('捕获除零异常') 
except NameError: 
    print('捕获名称异常')
```

```python
try: 
    print(a) 
    10 / 0 
except (ZeroDivisionError, NameError): 
    print('捕获到异常')
```

```python
try: 
    print(a) 
    10 / 0 
except Exception: 
    print('捕获到异常')
```


```python
#!/usr/bin/env python
#-*- coding:utf8 -*-
try:
    open("tes.txt")

except (KeyError,IndexError) as e :
    print("没有这个key",e)

except IndexError as e :
    print("列表操作错误",e)

except Exception as e:
    print("未知错误",e)

else:
    print("一切正常")

finally:
    print("不管有没有错，都执行")
```


```python
import traceback 
try: 
    10 / 0 
except Exception as e: 
    traceback.print_exc() # 命令行输出堆栈信息
    info = traceback.format_exc() # 保存堆栈信息到变量， 内容与上面语句一致
    print(info)
```

```python
try: 
    10 / 2 
except Exception as e: 
    print("发生异常") 
else: 
    print('没有异常') 
finally: 
    print("始终执行")
```


## 异常抛出

```python
try: 
    raise ValueError("用户输入数值错误") 
except Exception as e: 
    print(e)
```



## 自定义异常



```python
#!/usr/bin/env python
# -*- coding:utf8 -*-
# auther; 18793
# Date：2019/9/8 21:07
# filename: 07.自定义异常.py

class MyError(Exception):
    def __init__(self):
        pass

    def __str__(self):
        return "this is self define error"


def my_error_test():
    try:
        raise MyError()
    except MyError as e:
        print("Exception info: ", e)


my_error_test()  # Exception info:  this is self define error
```


```python
#!/usr/bin/env python
#-*- coding:utf8 -*-

#继承Exception类
class MyError(Exception):
    pass

#需要异常类有一定的提示信息,可以重载__init__和__str__两个方法
class RangeError(Exception):
    def __init__(self,value):
        self.value = value

    def __str__(self):
        return self.value


if __name__ == '__main__':
    raise RuntimeError("Range Error....!")      #调用raise 抛出异常
```